// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class T1loginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void t1login() {
    driver.get("https://xiumi.us/#/");
    assertThat(driver.findElement(By.linkText("登录")).getText(), is("登录"));
    assertThat(driver.findElement(By.linkText("登录")).getText(), is("登录"));
    driver.findElement(By.cssSelector(".auth-bar")).click();
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("2087606307@qq.com");
    driver.findElement(By.cssSelector(".login-page")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("abcdefg");
    driver.findElement(By.cssSelector(".login-chapter")).click();
    driver.findElement(By.cssSelector(".login-page")).click();
    driver.findElement(By.name("captcha")).click();
    driver.findElement(By.name("captcha")).sendKeys("THKY");
    driver.findElement(By.cssSelector(".btn-red")).click();
    driver.findElement(By.cssSelector(".col-sm-12")).click();
    assertThat(driver.findElement(By.cssSelector(".col-sm-12")).getText(), is("出错了：验证码错误"));
    assertThat(driver.findElement(By.cssSelector(".col-sm-12")).getText(), is("出错了：验证码错误"));
  }
}
